/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventanas;
import Clases.Convertidor;
import java.awt.Image;
import java.awt.Toolkit;
/**
 *
 * @author MaynorPC
 */
public class Conversor extends javax.swing.JFrame {

    /**
     * Creates new form Conversor
     */
    public Conversor() {
        initComponents();
        this.setLocationRelativeTo(null);
    }
 public Image getIconImage(){
    Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("Imagenes/logo.png"));
    return retValue;
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Salir = new javax.swing.JButton();
        Regresar = new javax.swing.JButton();
        Saludo = new javax.swing.JLabel();
        Numero = new javax.swing.JTextField();
        jBinario = new javax.swing.JLabel();
        Binario = new javax.swing.JLabel();
        jOctal = new javax.swing.JLabel();
        Octal = new javax.swing.JLabel();
        JHex = new javax.swing.JLabel();
        Hex = new javax.swing.JLabel();
        Fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Salir.setBackground(new java.awt.Color(204, 0, 0));
        Salir.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Salir.setText("Salir");
        Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalirActionPerformed(evt);
            }
        });
        getContentPane().add(Salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 0, -1, -1));

        Regresar.setBackground(new java.awt.Color(204, 0, 0));
        Regresar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Regresar.setText("Volver al Menu");
        Regresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegresarActionPerformed(evt);
            }
        });
        getContentPane().add(Regresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 500, -1, -1));

        Saludo.setBackground(new java.awt.Color(204, 0, 0));
        Saludo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Saludo.setText("Ingrese el decimal que desea convertir:");
        getContentPane().add(Saludo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, -1));

        Numero.setBackground(new java.awt.Color(204, 0, 0));
        Numero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NumeroActionPerformed(evt);
            }
        });
        getContentPane().add(Numero, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 110, 200, -1));

        jBinario.setBackground(new java.awt.Color(204, 0, 0));
        jBinario.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jBinario.setText("Numero Binario:");
        getContentPane().add(jBinario, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, -1, -1));

        Binario.setBackground(new java.awt.Color(204, 0, 0));
        Binario.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Binario.setText("..");
        getContentPane().add(Binario, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 230, -1, -1));

        jOctal.setBackground(new java.awt.Color(204, 0, 0));
        jOctal.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jOctal.setText("Numero Octal:");
        getContentPane().add(jOctal, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, -1, -1));

        Octal.setBackground(new java.awt.Color(204, 0, 0));
        Octal.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Octal.setText("...");
        getContentPane().add(Octal, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 340, -1, -1));

        JHex.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        JHex.setText("Numero Hexadecimal:");
        getContentPane().add(JHex, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 390, -1, -1));

        Hex.setBackground(new java.awt.Color(204, 0, 0));
        Hex.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Hex.setText("...");
        getContentPane().add(Hex, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 440, -1, -1));

        Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondo.jpg"))); // NOI18N
        getContentPane().add(Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 386, 525));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalirActionPerformed
   System.exit(0);
    }//GEN-LAST:event_SalirActionPerformed

    private void RegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegresarActionPerformed
 Menu menu = new Menu ();
   menu.setVisible(true);
   this.dispose();
    }//GEN-LAST:event_RegresarActionPerformed

    private void NumeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NumeroActionPerformed
   String Num=null;
   Num=Numero.getText();
   Convertidor CN = new Convertidor();
   Hex.setText(CN.intoHex(new Integer(Num)));
   Octal.setText(CN.intoOct(new Integer(Num)));
   Binario.setText(CN.intoBin(new Integer(Num)));
   
   
    }//GEN-LAST:event_NumeroActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Conversor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Conversor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Conversor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Conversor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Conversor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Binario;
    private javax.swing.JLabel Fondo;
    private javax.swing.JLabel Hex;
    private javax.swing.JLabel JHex;
    private javax.swing.JTextField Numero;
    private javax.swing.JLabel Octal;
    private javax.swing.JButton Regresar;
    private javax.swing.JButton Salir;
    private javax.swing.JLabel Saludo;
    private javax.swing.JLabel jBinario;
    private javax.swing.JLabel jOctal;
    // End of variables declaration//GEN-END:variables
}
