/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventanas;

import java.awt.Image;
import java.awt.Toolkit;

/**
 *
 * @author MaynorPC
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
        this.setLocationRelativeTo(null);
        Principal principal = new Principal ();
        jNombre.setText(principal.x);
    }
 public Image getIconImage(){
    Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("Imagenes/logo.png"));
    return retValue;
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Salir = new javax.swing.JButton();
        Regresar = new javax.swing.JButton();
        Saludo = new javax.swing.JLabel();
        jNombre = new javax.swing.JLabel();
        Conversor = new javax.swing.JButton();
        Digitos = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        Derivar = new javax.swing.JButton();
        Fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Salir.setBackground(new java.awt.Color(204, 0, 0));
        Salir.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Salir.setText("Salir");
        Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalirActionPerformed(evt);
            }
        });
        getContentPane().add(Salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 0, -1, -1));

        Regresar.setBackground(new java.awt.Color(204, 0, 0));
        Regresar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Regresar.setText("Ir al Login");
        Regresar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RegresarMouseClicked(evt);
            }
        });
        Regresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegresarActionPerformed(evt);
            }
        });
        getContentPane().add(Regresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        Saludo.setBackground(new java.awt.Color(204, 0, 0));
        Saludo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Saludo.setText("Iniciaste sesion como:");
        getContentPane().add(Saludo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 520, -1, -1));

        jNombre.setBackground(new java.awt.Color(204, 0, 0));
        jNombre.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jNombre.setText("....");
        getContentPane().add(jNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 520, 300, 20));

        Conversor.setBackground(new java.awt.Color(204, 0, 0));
        Conversor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/math.png"))); // NOI18N
        Conversor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConversorActionPerformed(evt);
            }
        });
        getContentPane().add(Conversor, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 80, -1));

        Digitos.setBackground(new java.awt.Color(204, 0, 0));
        Digitos.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Digitos.setText("Conversor de Digitos");
        getContentPane().add(Digitos, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, -1));

        jLabel2.setBackground(new java.awt.Color(204, 0, 0));
        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setText("Funciones");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 70, -1, -1));

        jLabel1.setBackground(new java.awt.Color(204, 0, 0));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Derivacion");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, -1, -1));

        Derivar.setBackground(new java.awt.Color(204, 0, 0));
        Derivar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Derivar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Derivacion.jpg"))); // NOI18N
        Derivar.setToolTipText("");
        Derivar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DerivarActionPerformed(evt);
            }
        });
        getContentPane().add(Derivar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, 70, -1));

        Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondo.jpg"))); // NOI18N
        getContentPane().add(Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 502, 570));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalirActionPerformed
       System.exit(0);
    }//GEN-LAST:event_SalirActionPerformed

    private void RegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegresarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RegresarActionPerformed

    private void RegresarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RegresarMouseClicked
   Principal principal = new Principal ();
   principal.setVisible(true);
   this.dispose();
    }//GEN-LAST:event_RegresarMouseClicked

    private void ConversorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConversorActionPerformed
Conversor conversor = new Conversor ();
   conversor.setVisible(true);
   this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_ConversorActionPerformed

    private void DerivarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DerivarActionPerformed
  Polinomio polinomio = new Polinomio ();
   polinomio.setVisible(true);
   this.dispose();
    }//GEN-LAST:event_DerivarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Conversor;
    private javax.swing.JButton Derivar;
    private javax.swing.JLabel Digitos;
    private javax.swing.JLabel Fondo;
    private javax.swing.JButton Regresar;
    private javax.swing.JButton Salir;
    private javax.swing.JLabel Saludo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jNombre;
    // End of variables declaration//GEN-END:variables
}
